### ISSUE TITLE
Integrate this backend into Django core

### ISSUE THREAD

**Issue by claudep** [django-pymemcache/django-pymemcache#25]
Django has an accepted ticket for integrating a pymemcache backend.
https://code.djangoproject.com/ticket/29887

What about preparing a patch to integrate this package code into Django?

**Comment by ngnpope** [comment]
@claudep I dusted off something I started over 18 months ago: https://github.com/django/django/pull/13310

**Comment by claudep** [comment]
Hey Nick, awesome!
