### ISSUE TITLE
Add TLS support

### ISSUE THREAD

**Issue by moisesguimaraes** [django-pymemcache/django-pymemcache#26]
Since version 1.5.13, Memcached [supports TLS](https://github.com/memcached/memcached/wiki/TLS).

Since version 3.1.0, python-binary-memecached [supports TLS](https://github.com/pinterest/pymemcache/releases/tag/v3.1.0).

**Comment by ngnpope** [comment]
IIUC this should just work already? Can you not do something like the following in your ``settings.py``:

```python
import ssl

CACHES = {
    'default': {
        'BACKEND': 'djpymemcache.backend.PyMemcacheCache',
        'LOCATION': ['127.0.0.1:11211'],
        'OPTIONS': {'tls_context': ssl.create_default_context(cafile='my-ca-root.crt')},
    },
}
```

**Comment by moisesguimaraes** [comment]
Indeed it works @pope1ni.

Thanks for the hint o/
